name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Environment
      run: rustup target add i686-unknown-linux-gnu
    - name: Setup Packages
      run: sudo apt install pkg-config libssl-dev
    - name: Build
      run: cargo build --target=i686-unknown-linux-gnu
